-- 初始化审批模板数据
INSERT INTO biz_approval_template (template_code, template_name, version, config_json, process_definition_key, status, create_time, update_time)
VALUES ('PURCHASE_001', '通用采购审批流', 1,
'{"templateCode":"PURCHASE_001","templateName":"通用采购审批流","version":1,"globalConfig":{"startNode":"Start","endNode":"End"},"nodes":[{"nodeId":"Start","nodeName":"开始","nodeType":"startEvent","nextNodes":{"next":"Approve1"}},{"nodeId":"Approve1","nodeName":"主管审批","nodeType":"userTask","assigneeType":"user","assigneeValue":"manager","nextNodes":{"APPROVE":"Approve2","REJECT":"End"},"conditions":{"APPROVE":{"expression":"${approve_result == ''APPROVE''}"},"REJECT":{"expression":""}}},{"nodeId":"Approve2","nodeName":"总监审批","nodeType":"userTask","assigneeType":"user","assigneeValue":"director","nextNodes":{"next":"End"}},{"nodeId":"End","nodeName":"结束","nodeType":"endEvent","nextNodes":{}}]}',
'PURCHASE_001', 'CREATED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO biz_approval_template (template_code, template_name, version, config_json, process_definition_key, status, create_time, update_time)
VALUES ('LEAVE_001', '请假审批流', 4,
'{"templateCode":"LEAVE_001","templateName":"请假审批流","version":1,"globalConfig":{"startNode":"Start","endNode":"End"},"nodes":[{"nodeId":"Start","nodeName":"开始","nodeType":"startEvent","nextNodes":{"next":"DirectManager"}},{"nodeId":"DirectManager","nodeName":"直接主管审批","nodeType":"userTask","assigneeType":"user","assigneeValue":"${direct_manager}","nextNodes":{"APPROVE":"DaysCheck","REJECT":"End"},"conditions":{"APPROVE":{"expression":"${approve_result == ''APPROVE''}","next":"DaysCheck"},"REJECT":{"expression":"${approve_result == ''REJECT''}","next":"End"}}},{"nodeId":"DaysCheck","nodeName":"请假天数检查","nodeType":"exclusiveGateway","nextNodes":{"short":"HR","long":"SeniorManager"},"conditions":{"short":{"expression":"${leave_days <= 3}","next":"HR"},"long":{"expression":"${leave_days > 3}","next":"SeniorManager"}}},{"nodeId":"SeniorManager","nodeName":"上级主管审批(>3天)","nodeType":"userTask","assigneeType":"user","assigneeValue":"${senior_manager}","nextNodes":{"APPROVE":"HR","REJECT":"End"},"conditions":{"APPROVE":{"expression":"${approve_result == ''APPROVE''}","next":"HR"},"REJECT":{"expression":"${approve_result == ''REJECT''}","next":"End"}}},{"nodeId":"HR","nodeName":"HR审批","nodeType":"userTask","assigneeType":"user","assigneeValue":"${hr}","nextNodes":{"next":"End"}},{"nodeId":"End","nodeName":"结束","nodeType":"endEvent","nextNodes":{}}]}',
'LEAVE_001', 'DEPLOYED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO biz_approval_template (template_code, template_name, version, config_json, process_definition_key, status, create_time, update_time)
VALUES ('EXPENSE_001', '费用报销审批流', 1,
'{"templateCode":"EXPENSE_001","templateName":"费用报销审批流","version":1,"globalConfig":{"startNode":"Start","endNode":"End"},"nodes":[{"nodeId":"Start","nodeName":"开始","nodeType":"startEvent","nextNodes":{"next":"ExpenseApprove"}},{"nodeId":"ExpenseApprove","nodeName":"费用审批","nodeType":"userTask","assigneeType":"user","assigneeValue":"finance","nextNodes":{"next":"End"}},{"nodeId":"End","nodeName":"结束","nodeType":"endEvent","nextNodes":{}}]}',
'EXPENSE_001', 'CREATED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
