CREATE TABLE IF NOT EXISTS biz_approval_template (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_code VARCHAR(50) NOT NULL,
  template_name VARCHAR(100) NOT NULL,
  version INT NOT NULL,
  config_json CLOB,
  process_definition_key VARCHAR(100),
  deployment_id VARCHAR(100),
  status VARCHAR(20),
  create_time TIMESTAMP,
  update_time TIMESTAMP,
  CONSTRAINT uk_template_code UNIQUE (template_code)
);

CREATE TABLE IF NOT EXISTS biz_approval_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_code VARCHAR(50),
  business_key VARCHAR(100),
  process_instance_id VARCHAR(100),
  task_id VARCHAR(100),
  operation VARCHAR(20),
  operator VARCHAR(50),
  comments CLOB,
  status VARCHAR(20),
  create_time TIMESTAMP
);

CREATE TABLE IF NOT EXISTS biz_event_message (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type VARCHAR(50),
  business_key VARCHAR(100),
  process_instance_id VARCHAR(100),
  event_data CLOB,
  status VARCHAR(20),
  retry_count INT DEFAULT 0,
  create_time TIMESTAMP,
  update_time TIMESTAMP
);

CREATE TABLE IF NOT EXISTS biz_compensation_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  process_instance_id VARCHAR(100),
  business_key VARCHAR(100),
  compensation_topic VARCHAR(100),
  compensation_params CLOB,
  status VARCHAR(20),
  error_message CLOB,
  create_time TIMESTAMP,
  update_time TIMESTAMP
);
